In [7]:
import numpy as np
import pandas as pd

In [8]:
# Load File
df = pd.read_csv('/content/Language Detection.csv')

df.head()

Text Language
0   Nature, in the broadest sense, is the natural...  English
1  "Nature" can refer to the phenomena of the phy...  English
2  The study of nature is a large, if not the onl...  English
3  Although humans are part of nature, human acti...  English
4  [1] The word nature is borrowed from the Old F...  English

In [9]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [10]:
df.tail()

Text Language
10332  ನಿಮ್ಮ ತಪ್ಪು ಏನು ಬಂದಿದೆಯೆಂದರೆ ಆ ದಿನದಿಂದ ನಿಮಗೆ ಒ...  Kannada
10333  ನಾರ್ಸಿಸಾ ತಾನು ಮೊದಲಿಗೆ ಹೆಣಗಾಡುತ್ತಿದ್ದ ಮಾರ್ಗಗಳನ್...  Kannada
10334  ಹೇಗೆ ' ನಾರ್ಸಿಸಿಸಮ್ ಈಗ ಮರಿಯನ್ ಅವರಿಗೆ ಸಂಭವಿಸಿದ ಎ...  Kannada
10335  ಅವಳು ಈಗ ಹೆಚ್ಚು ಚಿನ್ನದ ಬ್ರೆಡ್ ಬಯಸುವುದಿಲ್ಲ ಎಂದು ...  Kannada
10336  ಟೆರ್ರಿ ನೀವು ನಿಜವಾಗಿಯೂ ಆ ದೇವದೂತನಂತೆ ಸ್ವಲ್ಪ ಕಾಣು...  Kannada

In [11]:
df['Language'].value_counts()

English       1385
French        1014
Spanish        819
Portugeese     739
Italian        698
Russian        692
Sweedish       676
Malayalam      594
Dutch          546
Arabic         536
Turkish        474
German         470
Tamil          469
Danish         428
Kannada        369
Greek          365
Hindi           63
Name: Language, dtype: int64

# Split

In [12]:
x=df['Text']
y=df['Language']
x
y

0        English
1        English
2        English
3        English
4        English
          ...   
10332    Kannada
10333    Kannada
10334    Kannada
10335    Kannada
10336    Kannada
Name: Language, Length: 10337, dtype: object

# Label encoding

In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [14]:
y

array([3, 3, 3, ..., 9, 9, 9])

In [15]:
import pickle
with open('label encoder.pkl','wb') as f:
  pickle.dump(le, f)

# Text preprocessing

In [16]:
import re
df_list=[]
for Text in x:
  Text=re.sub(r'[!@#$(),\n"%^&*:;~0-9]', '',Text)
  Text=re.sub('[[]]','',Text)
  Text=Text.lower()
  df_list.append(Text)

<ipython-input-16-963b2d4387f0>:5: FutureWarning: Possible nested set at position 1
  Text=re.sub('[[]]','',Text)


# Vectorization

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
x=cv.fit_transform(df_list).toarray()

In [18]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [19]:
import pickle
with open('count_vectorizer.pkl','wb') as f:
  pickle.dump(cv, f)

In [20]:
x.shape

(10337, 39419)

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [22]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train,y_train)

MultinomialNB()

In [23]:
y_pred=model.predict(x_test)

In [24]:
import pickle
with open('model1.pkl','wb') as file:
  pickle.dump(model,file)

In [25]:
from sklearn.metrics import classification_report,accuracy_score,confusion_matrix
report=classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       1.00      0.98      0.99       113
           1       0.98      0.95      0.97        88
           2       0.97      0.94      0.95        98
           3       0.90      1.00      0.95       290
           4       0.98      0.99      0.98       215
           5       1.00      0.96      0.98        93
           6       1.00      0.98      0.99        83
           7       1.00      0.92      0.96        12
           8       1.00      1.00      1.00       140
           9       1.00      0.97      0.99        79
          10       0.98      0.98      0.98       111
          11       0.98      0.99      0.99       131
          12       1.00      0.97      0.98       127
          13       0.99      0.97      0.98       175
          14       0.98      0.97      0.97       140
          15       1.00      0.99      0.99        83
          16       1.00      0.91      0.95        90

    accuracy              

In [26]:
accuracy=accuracy_score(y_test,y_pred)
print("Accuracy:",accuracy*100)

Accuracy: 97.63056092843327


In [27]:
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[111   0   0   2   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0  84   0   1   1   0   0   0   0   0   0   0   0   0   2   0   0]
 [  0   0  92   4   1   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0   0 289   1   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1   1 213   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   1   2   0  89   0   0   0   0   0   0   0   0   1   0   0]
 [  0   0   0   1   0   0  81   0   0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0  11   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 140   0   0   0   0   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0  77   0   0   0   0   0   0   0]
 [  0   0   0   2   0   0   0   0   0   0 109   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   0   0   0   0 130   0   0   0   0   0]
 [  0   0   0   4   0   0   0   0   0   0   0   0 123   0   0   0   0]
 [  0   0   0   3   0   0   0   0   0   0   0   2   0 170   0   0   0]
 [  0 

# Prediction

In [28]:
user=input("Enter a text:")
data=cv.transform([user]).toarray()
output=model.predict(data)
print(output)

Enter a text:app
[3]


In [29]:
lang=le.inverse_transform(output)
lang

array(['English'], dtype=object)